# Generated by Django 3.1.3 on 2024-02-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20240214_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='common/profile', verbose_name='프로필 이미지'),
        ),
    ]
