# Generated by Django 3.1.3 on 2024-02-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20240215_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
