# Generated by Django 4.2.10 on 2024-02-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0005_question_file_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="advertisement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="common/profile",
                        verbose_name="프로필 이미지",
                    ),
                ),
            ],
        ),
    ]
