# Generated by Django 4.2.10 on 2024-02-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0006_advertisement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="advertisement",
        ),
    ]
