# Generated by Django 4.2.10 on 2024-02-27 00:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0008_advertisement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
