# Generated by Django 4.2.10 on 2024-02-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0009_alter_question_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="file_upload",
            field=models.FileField(blank=True, null=True, upload_to="files/%Y/%m/%d/"),
        ),
    ]
